version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: quantconsole-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: quantconsole123
      MYSQL_DATABASE: quantconsole
      MYSQL_USER: quantuser
      MYSQL_PASSWORD: quantpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quantconsole-network

  # Redis (用于缓存和会话存储)
  redis:
    image: redis:7-alpine
    container_name: quantconsole-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quantconsole-network

  # phpMyAdmin (数据库管理工具)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quantconsole-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: quantconsole123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - quantconsole-network

volumes:
  mysql_data:
  redis_data:

networks:
  quantconsole-network:
    driver: bridge
